name: 'NPM & VSCE Marketplace Publishing'
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      # `secrets.NPM_TOKEN` references a GitHub Secret configured for this repo or organization,
      # and is used to authenticate for the NPM publish command.
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # This is for the VSCode Extension Marketplace Personal Access Token
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      # actions/checkout required for dorny/paths-filter to work
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # This step checks for changes in the packages against the main branch and this
      # boolean can be picked up inside steps.changes.outputs
      - uses: dorny/paths-filter@v2
        name: 'Checking for changes in each package'
        id: changes
        with:
          base: main
          filters: |
            create-loop:
              - 'create-loop/**'
            loop-templates:
              - 'loop-templates/**'
            vscode-extension:
              - 'vscode-extension/**'

      - run: npm set audit false

      # Publishing create-loop to npm
      - if: steps.changes.outputs.create-loop == 'true'
        name: 'Publishing create-loop'
        working-directory: ./create-loop
        run: |
          echo 'create-loop changed!'
          npm run build-templates
          npm ci
          npm run build --if-present
          printf '\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access public

      - if: steps.changes.outputs.create-loop == 'false'
        run: echo 'No changes detected in create-loop'

      # Publishing loop-templates to npm
      - if: steps.changes.outputs.loop-templates == 'true'
        name: 'Publishing loop-templates'
        working-directory: ./loop-templates
        run: |
          echo 'loop-templates changed!'
          npm ci
          npm run build --if-present
          printf '\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access public

      - if: steps.changes.outputs.loop-templates == 'false'
        run: echo 'No changes detected in loop-templates'

      # Publishing vscode-extension to VSCode Extension Marketplace
      - if: steps.changes.outputs.vscode-extension == 'true'
        name: 'Publishing vscode-extension'
        working-directory: ./vscode-extension
        run: |
          echo 'vscode-extension changed!'
          npm run build-templates
          npm ci
          npm run build --if-present
          npm run deploy

      - if: steps.changes.outputs.vscode-extension == 'false'
        run: echo 'No changes detected in vscode-extension'
